name: Tests and Coverage
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make update
      - run: make install
      - run: make test
      - run: make lint
      
      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover .phpunit.cache/code-coverage/clover.xml
      
      - name: Upload coverage to qlty.sh
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: b.phpunit.cache/code-coverage/clover.xml