name: testworkflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      - run: make update
      - run: make install
      - run: make test
      - run: make lint
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      # NOTE: uncomment for using workflow
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v9
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true